import localFont from "next/font/local";
import { Analytics } from "@vercel/analytics/react";

import "./globals.css";

import { DM_Sans } from "next/font/google";
const dmsans = DM_Sans({
  subsets: ["latin"],
  // weight: [400, 700],
});

import Script from "next/script";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script
        src="https://widget.cxgenie.ai/widget.js"
        data-aid="1a281559-dd6b-4197-9ade-231289a0b4c1"
        data-lang="en"
      />
      <body className={`${dmsans.className} antialiased`}>
        {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > */}
        <Analytics />
        {children}
      </body>
    </html>
  );
}
